package main

var (
	Instance     = make(map[string]string)
	AlertState   = make(map[string]string)
	Metric       = make(map[string]string)
	InstanceType = make(map[string]string)
	Expression   = make(map[string]string)
)

func init() {
	Metric["Host.mem.used"] = "量用内存"
	Metric["Host.disk.writebytes"] = "磁盘每秒写入的字节数"
	Metric["Host.cpu.system"] = "当前内核空间占用CPU百分比"
	Metric["Host.diskussage.total"] = "磁盘存储总量"
	Metric["Host.netout.rate"] = "网卡每秒发送的比特数"
	Metric["Host.tcpconnection"] = "各种状态下的TCP连接数包括"
	Metric["Host.load15"] = "过去15分钟的系统平均负载"
	Metric["Host.diskusage.used"] = "磁盘的已用存储空间"
	Metric["Host.load5"] = "过去5分钟的系统平均负载"
	Metric["Host.disk.writeiops"] = "磁盘每秒的写请求数量"
	Metric["Host.fs.inode"] = "inode使用率"
	Metric["Host.netin.errorpackage"] = "设备驱动器检测到的接收错误包的数量"
	Metric["Host.cpu.idle"] = "当前空闲CPU百分比"
	Metric["Host.cpu.other"] = "其他占用CUP百分比"
	Metric["Host.disk.readbytes"] = "磁盘每秒读取的字节数"
	Metric["Host.disk.readiops"] = "磁盘每秒的读请求数量"
	Metric["Host.mem.actualused"] = "用户实际使用的内存"
	Metric["Host.mem.free"] = "剩余内存量"
	Metric["Host.netout.packages"] = "网卡每秒发送的数据包数"
	Metric["Host.netout.errorpackages"] = "设备驱动器检测到的发送错误包的数量"
	Metric["Host.mem.total"] = "内存总量"
	Metric["Host.mem.freeutilization"] = "剩余内存百分比"
	Metric["Host.disk.utilization"] = "磁盘使用率"
	Metric["Host.diskusage.free"] = "磁盘的剩余存储空间"
	Metric["Host.load1"] = "过去1分钟的系统平均负载"
	Metric["Host.netin.rate"] = "网卡每秒接收的比特数"
	Metric["Host.netin.packages"] = "网卡每秒接收的数据包数"
	Metric["Host.cpu.user"] = "当前用户空间占用CPU百分比"
	Metric["Host.cpu.iowait"] = "当前等待IO操作的CPU百分比"
	Metric["Host.cpu.totalUsed"] = "当前消耗的总CPU百分比"
	Metric["Host.mem.usedutilization"] = "内存使用率"

	AlertState["OK"] = "恢复正常"
	AlertState["ALERT"] = "发生告警"
	AlertState["INSUFFICIENT_DATA"] = "不重要"

	Instance["i-t4n3da0anpqygm12qauu"] = "blhx-ys-tw-al-prod-all-game2-1"
	Instance["i-t4n2qbgrfj20fsmotfhv"] = "platform-ys-tw-prod-server2"
	Instance["i-t4n2erb4fu23q1h921bd"] = "worker-k8s-for-cs-c014f4c1195ff4095819b5804adec8a67"
	Instance["i-t4n603l3nn58k31tmqn5"] = "blhx-ys-tw-al-prod-all-game5-1"
	Instance["i-t4n0f9lrwq9j5cf3bof1"] = "blhx-ys-tw-al-prod-all-umnesia4-1"
	Instance["i-t4ngbrhmsy81varv99gz"] = "blhx-ys-tw-al-prod-all-mnesia2-1"
	Instance["i-t4n687x3nzdt47zf02ww"] = "blhx-ys-tw-al-prod-all-umnesia5-1"
	Instance["i-t4n6xq3p9bih0rfpmy8o"] = "blhx-ys-tw-al-prod-all-pmnem-1"
	Instance["i-t4ngc1hiv72uy6i5j9mw"] = "platform-ys-tw-prod-server1"
	Instance["i-t4n687x3nzdt47zf02wv"] = "blhx-ys-tw-al-prod-all-mnesia5-1"
	Instance["i-t4n54q240rx1ltw81q9h"] = "blhx-ys-tw-al-prod-all-loginmnem-1"
	Instance["i-t4ngzxzgmqjmiu8fpiyz"] = "blhx-ys-tw-al-prod-all-login-1"
	Instance["i-t4n2bg44b7y7eeha47u4"] = "blhx-ys-tw-al-prod-all-mnesia1-1"
	Instance["i-t4n7dkpn64ef0dhrerks"] = "platform_test"
	Instance["i-t4n59njs9svbe7x2nbrt"] = "platform-ys-tw-prod-server3"
	Instance["i-t4ne1o8m3n6jato9jx0b"] = "worker-k8s-for-cs-c6533d44d42e84a19b96a49d72d270ac6"
	Instance["i-t4ne1o8m3n6jato9jx0c"] = "worker-k8s-for-cs-c6533d44d42e84a19b96a49d72d270ac6"
	Instance["i-t4ngi2zltgxtp9g1n2q2"] = "blhx-ys-tw-prod-all-gm"
	Instance["i-t4n9dyppt1igr6fnucfv"] = "blhx-gitlab"
	Instance["i-t4n517hncuo5ajwdzapu"] = "base_server_openldap"
	Instance["i-t4n3da0anpqygm12qaut"] = "blhx-ys-tw-al-prod-all-game3-1"
	Instance["i-t4n8a3rkjlptiq47i4b3"] = "blhx-ys-tw-al-prod-all-umnesia1-1"
	Instance["i-t4nigy741uskioedg5tf"] = "blhx-ys-tw-al-prod-all-pay-1"
	Instance["i-t4n0f9lrwq9j5cf3bof2"] = "blhx-ys-tw-al-prod-all-mnesia4-1"
	Instance["i-t4ngbrhmsy81varv99gy"] = "blhx-ys-tw-al-prod-all-umnesia3-1"
	Instance["i-t4n8a3rkjlptio56e2bj"] = "blhx-ys-tw-al-prod-all-game1-1"
	Instance["i-t4ncr604qfe551bo2ry1"] = "platform-ys-tw-prod-task"
	Instance["i-t4ngbrhmsy81varv99h1"] = "blhx-ys-tw-al-prod-all-umnesia2-1"
	Instance["i-t4n94e7bypr68hb2927m"] = "blhx-gmt"
	Instance["i-t4n2erb4fu23q1h921bc"] = "worker-k8s-for-cs-c014f4c1195ff4095819b5804adec8a67"
	Instance["i-t4n4eenjycypmhx2d6eb"] = "blhx-ys-tw-al-prod-all-login-1-2"
	Instance["i-t4n3m26hw61zkrclp3bi"] = "blhx-ys-tw-al-prod-all-game4-1"
	Instance["i-t4ngbrhmsy81varv99h0"] = "blhx-ys-tw-al-prod-all-mnesia3-1"

	InstanceType["=i-"] = "云主机"
	InstanceType["=rm-"] = "云数据库"
	InstanceType["=dbs"] = "数据库备份"
	InstanceType["=r-"] = "REDIS"

	Expression["Maximum"] = "最大值"
	Expression["Minimum"] = "最小值"
	Expression["Average"] = "平均值"

}
