package main

var (
	instance   = make(map[string]string)
	alertState = make(map[string]string)
	metric     = make(map[string]string)
)

func init() {
	metric["cpu_user"] = "当前用户空间占用CPU百分比"
	metric["networkin_errorpackages"] = "设备驱动器检测到的接收错误包的数量"
	metric["diskusage_total"] = "磁盘存储总量"
	metric["disk_readiops"] = "磁盘每秒的读请求数量"
	metric["diskusage_used"] = "磁盘的已用存储空间"
	metric["networkout_errorpackages"] = "设备驱动器检测到的发送错误包的数量"
	metric["cpu_idle"] = "当前空闲CPU百分比"
	metric["cpu_wait"] = "当前等待IO操作的CPU百分比"
	metric["cpu_total"] = "当前消耗的总CPU百分比"
	metric["memory_actualusedspace"] = "用户实际使用的内存"
	metric["memory_freespace"] = "剩余内存量"
	metric["memory_usedutilization"] = "内存使用率"
	metric["networkout_rate"] = "网卡每秒发送的比特数"
	metric["memory_freeutilization"] = "剩余内存百分比"
	metric["disk_readbytes"] = "磁盘每秒读取的字节数"
	metric["fs_inodeutilization"] = "inode使用率"
	metric["cpu_system"] = "当前内核空间占用CPU百分比"
	metric["cpu_other"] = "其他占用CUP百分比"
	metric["load_15m"] = "过去15分钟的系统平均负载"
	metric["diskusage_utilization"] = "磁盘使用率"
	metric["networkout_packages"] = "网卡每秒发送的数据包数"
	metric["net_tcpconnection"] = "各种状态下的TCP连接数"
	metric["memory_usedspace"] = "量用内存"
	metric["load_5m"] = "过去5分钟的系统平均负载"
	metric["diskusage_free"] = "磁盘的剩余存储空间"
	metric["disk_writebytes"] = "磁盘每秒写入的字节数"
	metric["networkin_rate"] = "网卡每秒接收的比特数"
	metric["networkin_packages"] = "网卡每秒接收的数据包数"
	metric["memory_totalspace"] = "内存总量"
	metric["load_1m"] = "过去1分钟的系统平均负载"
	metric["disk_writeiops"] = "磁盘每秒的写请求数量"

	alertState["OK"] = "状态已恢复"
	alertState["ALERT"] = "发生告警"
	alertState["INSUFFICIENT_DATA "] = "不重要"

	instance["i-t4n3da0anpqygm12qauu"] = "blhx-ys-tw-al-prod-all-game2-1"
	instance["i-t4n2qbgrfj20fsmotfhv"] = "platform-ys-tw-prod-server2"
	instance["i-t4n2erb4fu23q1h921bd"] = "worker-k8s-for-cs-c014f4c1195ff4095819b5804adec8a67"
	instance["i-t4n603l3nn58k31tmqn5"] = "blhx-ys-tw-al-prod-all-game5-1"
	instance["i-t4n0f9lrwq9j5cf3bof1"] = "blhx-ys-tw-al-prod-all-umnesia4-1"
	instance["i-t4ngbrhmsy81varv99gz"] = "blhx-ys-tw-al-prod-all-mnesia2-1"
	instance["i-t4n687x3nzdt47zf02ww"] = "blhx-ys-tw-al-prod-all-umnesia5-1"
	instance["i-t4n6xq3p9bih0rfpmy8o"] = "blhx-ys-tw-al-prod-all-pmnem-1"
	instance["i-t4ngc1hiv72uy6i5j9mw"] = "platform-ys-tw-prod-server1"
	instance["i-t4n687x3nzdt47zf02wv"] = "blhx-ys-tw-al-prod-all-mnesia5-1"
	instance["i-t4n54q240rx1ltw81q9h"] = "blhx-ys-tw-al-prod-all-loginmnem-1"
	instance["i-t4ngzxzgmqjmiu8fpiyz"] = "blhx-ys-tw-al-prod-all-login-1"
	instance["i-t4n2bg44b7y7eeha47u4"] = "blhx-ys-tw-al-prod-all-mnesia1-1"
	instance["i-t4n7dkpn64ef0dhrerks"] = "platform_test"
	instance["i-t4n59njs9svbe7x2nbrt"] = "platform-ys-tw-prod-server3"
	instance["i-t4ne1o8m3n6jato9jx0b"] = "worker-k8s-for-cs-c6533d44d42e84a19b96a49d72d270ac6"
	instance["i-t4ne1o8m3n6jato9jx0c"] = "worker-k8s-for-cs-c6533d44d42e84a19b96a49d72d270ac6"
	instance["i-t4ngi2zltgxtp9g1n2q2"] = "blhx-ys-tw-prod-all-gm"
	instance["i-t4n9dyppt1igr6fnucfv"] = "blhx-gitlab"
	instance["i-t4n517hncuo5ajwdzapu"] = "base_server_openldap"
	instance["i-t4n3da0anpqygm12qaut"] = "blhx-ys-tw-al-prod-all-game3-1"
	instance["i-t4n8a3rkjlptiq47i4b3"] = "blhx-ys-tw-al-prod-all-umnesia1-1"
	instance["i-t4nigy741uskioedg5tf"] = "blhx-ys-tw-al-prod-all-pay-1"
	instance["i-t4n0f9lrwq9j5cf3bof2"] = "blhx-ys-tw-al-prod-all-mnesia4-1"
	instance["i-t4ngbrhmsy81varv99gy"] = "blhx-ys-tw-al-prod-all-umnesia3-1"
	instance["i-t4n8a3rkjlptio56e2bj"] = "blhx-ys-tw-al-prod-all-game1-1"
	instance["i-t4ncr604qfe551bo2ry1"] = "platform-ys-tw-prod-task"
	instance["i-t4ngbrhmsy81varv99h1"] = "blhx-ys-tw-al-prod-all-umnesia2-1"
	instance["i-t4n94e7bypr68hb2927m"] = "blhx-gmt"
	instance["i-t4n2erb4fu23q1h921bc"] = "worker-k8s-for-cs-c014f4c1195ff4095819b5804adec8a67"
	instance["i-t4n4eenjycypmhx2d6eb"] = "blhx-ys-tw-al-prod-all-login-1-2"
	instance["i-t4n3m26hw61zkrclp3bi"] = "blhx-ys-tw-al-prod-all-game4-1"
	instance["i-t4ngbrhmsy81varv99h0"] = "blhx-ys-tw-al-prod-all-mnesia3-1"
}
